#config_version=6

switches:
  #Cabinet Switches
  s_flipper_left:
    number: 3208-0
    tags: left_flipper
  s_flipper_right:
    number: 3208-1
    tags: right_flipper
  # Trough Switches
  s_trough_1:
    number: 3208-2
  s_trough_2:
    number: 3208-3
  s_trough_3:
    number: 3208-4
  s_trough_4:
    number: 3208-5
  s_plunger_lane:
    number: 3208-6
  # Upper Flipper
  s_flipper_upper:
    number: 3208-7
    tags: upper_flipper
  # Slingshots
  s_slingshot_left:
    number: 3208-10
    tags: slingshot
  s_slingshot_right:
    number: 3208-13
    tags: slingshot
  # EOS Switches
  s_flipper_left_eos:
    number: 3208-11
    tags: eos
  s_flipper_right_eos:
    number: 3208-12
    tags: eos
  s_flipper_upper_eos:
    number: 3208-16
    tags: eos
  # Inlanes / Outlanes
  s_left_outlane:
    number: 3208-8
  s_left_inlane:
    number: 3208-9
  s_right_inlane:
    number: 3208-14
  s_right_outlane:
    number: 3208-15
