#config_version=6

## MPF Main Machine Config File
#
# This file defines your system-wide properties like switches,
# drivers, ball devices, hardware platforms, and more. You can
# include everything here, or create sub-config files to be
# imported and merged with this one.

hardware:
  platform: fast

fast:
  net:
    controller: neuron
    port: auto
    io_loop:
      3208:
        model: FP-I/O-3208
        order: 1



#Config for Neuron controller and expansion boards. Playfield can be changed to any name, and this will what you will use for beginning address of each led on that expansion board (serial lets, WS2812, etc).

  exp: 
    boards:  
      neuron:
        model: FP-EXP-2000  
    port: auto
    baud: 921600
    debug: False

config:
  - config_switches.yaml
  - config_ball_devices.yaml
  - config_coils_flippers.yaml
modes:
  - attract
  - base

playfields:
  playfield:
    default_source_device: bd_trough
    tags: default




  